#!/bin/sh

# NOTE: it's better to not hardcode paths,
#       but get them relatively to `stdpath("data")`

rm -rf ~/.local/share/nvim/site/pack/
rm -rf ~/.config/nvim/lua/packer_compiled.lua

nvim +q
nvim
